'use client';

import React, { useState, useEffect, useCallback } from 'react';
import { Card, Badge, Button } from '@rn/brand';
import type { Brief } from '@rn/db';
import { useAuth } from '@rn/auth';

interface WarBoardProps {
  briefs: Brief[];
  onExitWarBoard: () => void;
}

export const WarBoard: React.FC<WarBoardProps> = ({ briefs, onExitWarBoard }) => {
  const { session, role } = useAuth();
  const [now, setNow] = useState(Date.now());
  const [commander, setCommander] = useState(session?.email || 'incident.commander@theripplenexus.com');
  const [postMortemLines, setPostMortemLines] = useState<string[]>([]);

  useEffect(() => {
    const t = setInterval(() => setNow(Date.now()), 1000);
    return () => clearInterval(t);
  }, []);

  // Only ops_lead and executive_admin may enter war board
  const canAccess = role === 'executive_admin' || role === 'operations_lead';

  const criticalBriefs = briefs.filter(
    (b) => b.priority === 'p0_critical' || b.priority === 'p1_high'
  );

  const generatePostMortem = useCallback(() => {
    const lines = [
      `## INCIDENT POST-MORTEM — ${new Date().toUTCString()}`,
      `**Incident Commander:** ${commander}`,
      `**Total P0/P1 Vectors in Scope:** ${criticalBriefs.length}`,
      '',
      '### Active Critical Briefs',
      ...criticalBriefs.map(
        (b) => `- [${b.priority.toUpperCase()}] **${b.title}** — Client: ${b.client_name || b.client_id} — Deadline: ${new Date(b.sla_deadline).toISOString()}`
      ),
      '',
      '### Timeline',
      `- War Board Activated: ${new Date(now).toISOString()}`,
      '- SLA Escalation Trigger: AUTO',
      '- Resolution: PENDING',
      '',
      '### Sensitive Data',
      '~~CREDENTIALS SCRUBBED BY CITADEL ENCLAVE~~',
      '',
      '*Generated by Ripple Nexus Hub War Board v2.1*',
    ];
    setPostMortemLines(lines);
  }, [criticalBriefs, commander, now]);

  if (!canAccess) {
    return (
      <div
        style={{
          padding: '2rem',
          backgroundColor: 'rgba(239,68,68,0.08)',
          border: '1px solid rgba(239,68,68,0.4)',
          borderRadius: '8px',
          textAlign: 'center',
          fontFamily: 'var(--font-mono, monospace)',
          color: '#EF4444',
          fontSize: '0.8125rem',
        }}
      >
        403 // WAR BOARD ACCESS RESTRICTED TO OPERATIONS LEAD & EXECUTIVE ADMIN
      </div>
    );
  }

  return (
    <div
      style={{
        position: 'fixed',
        inset: 0,
        zIndex: 8000,
        backgroundColor: '#05070A',
        backgroundImage:
          'linear-gradient(to right, rgba(239,68,68,0.06) 1px, transparent 1px), linear-gradient(to bottom, rgba(239,68,68,0.06) 1px, transparent 1px)',
        backgroundSize: '40px 40px',
        overflowY: 'auto',
        padding: '1.5rem',
      }}
    >
      {/* War Board Header */}
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          marginBottom: '1.5rem',
          flexWrap: 'wrap',
          gap: '1rem',
        }}
      >
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
          <span
            style={{
              width: '10px',
              height: '10px',
              borderRadius: '50%',
              backgroundColor: '#EF4444',
              boxShadow: '0 0 12px #EF4444',
              animation: 'pulse 1s infinite',
            }}
          />
          <span
            style={{
              fontFamily: 'var(--font-mono, monospace)',
              fontSize: '0.75rem',
              letterSpacing: '0.14em',
              color: '#EF4444',
              textTransform: 'uppercase',
            }}
          >
            // INCIDENT WAR-BOARD ACTIVE // {criticalBriefs.length} CRITICAL VECTORS
          </span>
        </div>

        <div style={{ display: 'flex', gap: '0.5rem', alignItems: 'center' }}>
          <span
            style={{
              fontFamily: 'var(--font-mono, monospace)',
              fontSize: '0.6875rem',
              color: '#8A99AD',
            }}
          >
            UTC: {new Date(now).toUTCString().split(' ')[4]}
          </span>
          <Button variant="secondary" size="sm" onClick={generatePostMortem}>
            GENERATE POST-MORTEM
          </Button>
          <Button variant="danger" size="sm" onClick={onExitWarBoard}>
            EXIT WAR BOARD
          </Button>
        </div>
      </div>

      {/* Critical Brief Cards */}
      <div
        style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fill, minmax(320px, 1fr))',
          gap: '1rem',
          marginBottom: '1.5rem',
        }}
      >
        {criticalBriefs.length === 0 ? (
          <Card>
            <div
              style={{
                textAlign: 'center',
                padding: '2rem',
                fontFamily: 'var(--font-mono, monospace)',
                color: '#00E599',
                fontSize: '0.875rem',
              }}
            >
              ✓ ALL CLEAR — NO CRITICAL VECTORS DETECTED
            </div>
          </Card>
        ) : (
          criticalBriefs.map((brief) => {
            const deadline = new Date(brief.sla_deadline).getTime();
            const remaining = deadline - now;
            const hoursLeft = Math.floor(remaining / 3600000);
            const minsLeft = Math.floor((remaining % 3600000) / 60000);
            const isBreached = remaining <= 0;

            return (
              <Card key={brief.id}>
                <div style={{ marginBottom: '0.5rem', display: 'flex', justifyContent: 'space-between' }}>
                  <Badge variant={brief.priority === 'p0_critical' ? 'critical' : 'warn'}>
                    {brief.priority.replace('_', ' ').toUpperCase()}
                  </Badge>
                  <span
                    style={{
                      fontFamily: 'var(--font-mono, monospace)',
                      fontSize: '0.6875rem',
                      color: '#8A99AD',
                    }}
                  >
                    {brief.client_name || brief.client_id}
                  </span>
                </div>

                <div
                  style={{
                    fontWeight: 700,
                    color: '#FFFFFF',
                    fontSize: '0.9375rem',
                    marginBottom: '0.5rem',
                  }}
                >
                  {brief.title}
                </div>

                <div
                  style={{
                    fontFamily: 'var(--font-mono, monospace)',
                    fontSize: '1.125rem',
                    fontWeight: 900,
                    color: isBreached ? '#EF4444' : hoursLeft < 2 ? '#F59E0B' : '#00D2FF',
                    letterSpacing: '0.04em',
                  }}
                >
                  {isBreached
                    ? '⚠ SLA BREACHED'
                    : `${hoursLeft}h ${minsLeft}m remaining`}
                </div>

                <div
                  style={{
                    marginTop: '0.75rem',
                    height: '4px',
                    borderRadius: '2px',
                    backgroundColor: '#1F2633',
                    overflow: 'hidden',
                  }}
                >
                  <div
                    style={{
                      height: '100%',
                      width: isBreached ? '100%' : `${Math.min(100, Math.max(0, ((1 - remaining / 172800000) * 100)))}%`,
                      backgroundColor: isBreached ? '#EF4444' : hoursLeft < 4 ? '#F59E0B' : '#0052FF',
                      transition: 'width 1s ease',
                    }}
                  />
                </div>
              </Card>
            );
          })
        )}
      </div>

      {/* Incident Commander Section */}
      <Card>
        <div
          style={{
            fontFamily: 'var(--font-mono, monospace)',
            fontSize: '0.625rem',
            letterSpacing: '0.08em',
            color: '#8A99AD',
            textTransform: 'uppercase',
            marginBottom: '0.5rem',
          }}
        >
          INCIDENT COMMANDER
        </div>
        <input
          type="text"
          value={commander}
          onChange={(e) => setCommander(e.target.value)}
          className="rn-input"
          style={{
            width: '100%',
            backgroundColor: '#0A0D12',
            border: '1px solid #EF4444',
            padding: '0.5rem 0.75rem',
            color: '#FFFFFF',
            borderRadius: '4px',
            fontFamily: 'var(--font-mono, monospace)',
            fontSize: '0.8125rem',
          }}
        />
      </Card>

      {/* Post-Mortem Output */}
      {postMortemLines.length > 0 && (
        <Card style={{ marginTop: '1rem' }}>
          <div
            style={{
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'center',
              marginBottom: '0.75rem',
            }}
          >
            <span
              style={{
                fontFamily: 'var(--font-mono, monospace)',
                fontSize: '0.75rem',
                color: '#00D2FF',
                textTransform: 'uppercase',
              }}
            >
              POST-MORTEM DOCUMENT
            </span>
            <button
              type="button"
              onClick={() => {
                const blob = new Blob([postMortemLines.join('\n')], { type: 'text/markdown' });
                const url = URL.createObjectURL(blob);
                const a = document.createElement('a');
                a.href = url;
                a.download = `rn-postmortem-${Date.now()}.md`;
                a.click();
                URL.revokeObjectURL(url);
              }}
              style={{
                backgroundColor: 'transparent',
                border: '1px solid #1F2633',
                color: '#00D2FF',
                padding: '4px 10px',
                borderRadius: '4px',
                fontFamily: 'var(--font-mono, monospace)',
                fontSize: '0.625rem',
                cursor: 'pointer',
              }}
            >
              DOWNLOAD .MD
            </button>
          </div>
          <pre
            style={{
              fontFamily: 'var(--font-mono, monospace)',
              fontSize: '0.75rem',
              color: '#8A99AD',
              lineHeight: 1.6,
              whiteSpace: 'pre-wrap',
              margin: 0,
            }}
          >
            {postMortemLines.join('\n')}
          </pre>
        </Card>
      )}
    </div>
  );
};
